export const MOVIES_LOADING = "MOVIES_LOADING"
export const MOVIES_LOADED_SUCCESS = "MOVIES_LOADED_SUCCESS"
export const MOVIES_LOADING_FAILURE = "MOVIES_LOADING_FAILURE"
export const TMDB_IMAGES_BASE_URL = "https://image.tmdb.org/t/p/original"

export const REACT_APP_TMDB_API_KEY = "5fb8f01c9da85d79758e14b1d83d35e3"
export const REACT_APP_TMDB_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1ZmI4ZjAxYzlkYTg1ZDc5NzU4ZTE0YjFkODNkMzVlMyIsInN1YiI6IjY1OGU2YjkzZDc1YmQ2Nzg5NjcyYmU5MCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WA9L3UH99f3VcDDVzROtOaxZUkKad1uYZkPyI48OK5w"


